/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Atividade05;

/**
 *
 * @author 2637207
 */
public class Exercicio01 extends javax.swing.JFrame {

    /**
     * Creates new form Exercicio01
     */
    public Exercicio01() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Doces:");

        jLabel2.setText("Salgados:");
        jLabel2.setToolTipText("");

        jLabel3.setText("Bolos:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Mês: Janeiro");

        jButton1.setText("Próximo mês");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton2.setText("Limpar");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(48, 48, 48)
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addGap(53, 53, 53))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int aux = 0;
    int vendas[][] = new int[3][6];
    String aux1 = "\t Doces \t Salgados \t Bolos";
    int totalDoces = 0, totalSalgados = 0, totalBolos = 0;

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        switch (aux) {
            case 0:
                vendas[0][0] = Integer.parseInt(jTextField1.getText());
                vendas[1][0] = Integer.parseInt(jTextField2.getText());
                vendas[2][0] = Integer.parseInt(jTextField3.getText());
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jLabel4.setText("Mês: Fevereiro");
                aux1 += "\nJaneiro: \t" + vendas[0][0] + " \t" + vendas[1][0] + "\t" + vendas[2][0];
                totalDoces += vendas[0][0];
                totalSalgados += vendas[1][0];
                totalBolos += vendas[2][0];
                aux += 1;
                jTextField1.requestFocus();
                break;
            case 1:
                vendas[0][1] = Integer.parseInt(jTextField1.getText());
                vendas[1][1] = Integer.parseInt(jTextField2.getText());
                vendas[2][1] = Integer.parseInt(jTextField3.getText());
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jLabel4.setText("Mês: Março");
                aux1 += "\nFevereiro: \t" + vendas[0][1] + " \t" + vendas[1][1] + "\t" + vendas[2][1];
                totalDoces += vendas[0][1];
                totalSalgados += vendas[1][1];
                totalBolos += vendas[2][1];
                aux += 1;
                jTextField1.requestFocus();
                break;
            case 2:
                vendas[0][2] = Integer.parseInt(jTextField1.getText());
                vendas[1][2] = Integer.parseInt(jTextField2.getText());
                vendas[2][2] = Integer.parseInt(jTextField3.getText());
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jLabel4.setText("Mês: Abril");
                aux1 += "\nMarço: \t" + vendas[0][2] + " \t" + vendas[1][2] + "\t" + vendas[2][2];
                totalDoces += vendas[0][2];
                totalSalgados += vendas[1][2];
                totalBolos += vendas[2][2];
                aux += 1;
                jTextField1.requestFocus();
                break;
            case 3:
                vendas[0][3] = Integer.parseInt(jTextField1.getText());
                vendas[1][3] = Integer.parseInt(jTextField2.getText());
                vendas[2][3] = Integer.parseInt(jTextField3.getText());
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jLabel4.setText("Mês: Maio");
                aux1 += "\nAbril: \t" + vendas[0][3] + " \t" + vendas[1][3] + "\t" + vendas[2][3];
                totalDoces += vendas[0][3];
                totalSalgados += vendas[1][3];
                totalBolos += vendas[2][3];
                jTextField1.requestFocus();
                aux += 1;
                break;
            case 4:
                vendas[0][4] = Integer.parseInt(jTextField1.getText());
                vendas[1][4] = Integer.parseInt(jTextField2.getText());
                vendas[2][4] = Integer.parseInt(jTextField3.getText());
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jLabel4.setText("Mês: Junho");
                aux1 += "\nMaio: \t" + vendas[0][4] + " \t" + vendas[1][4] + "\t" + vendas[2][4];
                totalDoces += vendas[0][4];
                totalSalgados += vendas[1][4];
                totalBolos += vendas[2][4];
                aux += 1;
                jButton1.setText("   Resultado   ");
                break;
            case 5:
                vendas[0][5] = Integer.parseInt(jTextField1.getText());
                vendas[1][5] = Integer.parseInt(jTextField2.getText());
                vendas[2][5] = Integer.parseInt(jTextField3.getText());
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                aux1 += "\nJunho: \t" + vendas[0][5] + " \t" + vendas[1][5] + "\t" + vendas[2][5];
                totalDoces += vendas[0][5];
                totalSalgados += vendas[1][5];
                totalBolos += vendas[2][5];
                aux += 1;
                aux1 += "\n\nTotal de Doces: " + totalDoces + "\nTotal de Salgados: " + totalSalgados
                        + "\nTotal de Bolos: " + totalBolos + "\nTotal: " + (totalDoces + totalSalgados + totalBolos);
                jTextField1.requestFocus();
                jButton1ActionPerformed(evt);
                break;
            default:
                aux = 0;
                jButton1.setEnabled(false);
                jTextField1.setEnabled(false);
                jTextField2.setEnabled(false);
                jTextField3.setEnabled(false);
                jButton2.setEnabled(true);
                for (int i = 0; i < 3; i++) {
                    for (int j = 0; j < 6; j++) {
                        vendas[i][j] = vendas[i][j];
                        jTextArea1.setText(aux1);
                    }
                }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextArea1.setText("");
        jButton1.setEnabled(true);
        aux = 0;
        jButton2.setEnabled(false);
        jLabel4.setText("Mês: Janeiro");
        jButton1.setText("Próximo mês");
        jTextField1.requestFocus();
        jTextField1.setEnabled(true);
        jTextField2.setEnabled(true);
        jTextField3.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercicio01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercicio01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercicio01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercicio01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercicio01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
